'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Arma
    Public Property Id As Integer
    Public Property Marca As String
    Public Property Modelo As String
    Public Property Calibre As String

    Public Overridable Property FuncionarioArma As ICollection(Of FuncionarioArma) = New HashSet(Of FuncionarioArma)

End Class
