'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FuncionarioEstadoLegal
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property Tipo As String
    Public Property Valor As String
    Public Property FechaRegistro As Date

    Public Overridable Property Funcionario As Funcionario

End Class
