'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Nomenclatura
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Codigo As String
    Public Property AreaResponsable As String
    Public Property Patron As String
    Public Property Ejemplo As String
    Public Property UbicacionArchivo As String
    Public Property Observaciones As String
    Public Property UsaFecha As Boolean
    Public Property UsaNomenclaturaCodigo As Boolean

End Class
