'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NovedadFuncionario
    Public Property Id As Integer
    Public Property NovedadId As Integer
    Public Property FuncionarioId As Integer

    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property Novedad As Novedad

End Class
