'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RegimenDetalle
    Public Property Id As Integer
    Public Property RegimenTrabajoId As Integer
    Public Property DiaSemana As Nullable(Of Byte)
    Public Property SemanaPar As Nullable(Of Boolean)
    Public Property FechaInicio As Nullable(Of Date)
    Public Property FechaFin As Nullable(Of Date)
    Public Property HoraDesde As Nullable(Of System.TimeSpan)
    Public Property HoraHasta As Nullable(Of System.TimeSpan)
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property RegimenTrabajo As RegimenTrabajo

End Class
