'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SumarioDetalle
    Public Property EstadoTransitorioId As Integer
    Public Property FechaDesde As Date
    Public Property FechaHasta As Nullable(Of Date)
    Public Property Observaciones As String
    Public Property Expediente As String
    Public Property FechaResolucion As Nullable(Of Date)

    Public Overridable Property EstadoTransitorio As EstadoTransitorio

End Class
