'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnidadGeneral
    Public Property UnidadGeneralId As Integer
    Public Property Nombre As String
    Public Property Codigo As String
    Public Property Descripcion As String
    Public Property EsActivo As Boolean
    Public Property FechaCreacion As Date
    Public Property FechaActualizacion As Nullable(Of Date)
    Public Property UsuarioCreacion As String
    Public Property UsuarioActualizacion As String
    Public Property Nombre_Normalizado As String

End Class
