'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property Id As Integer
    Public Property NombreUsuario As String
    Public Property PasswordHash As Byte()
    Public Property PasswordSalt As Byte()
    Public Property NombreCompleto As String
    Public Property Activo As Boolean
    Public Property FechaCreacion As Date
    Public Property FuncionarioId As Nullable(Of Integer)

    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property Rol As ICollection(Of Rol) = New HashSet(Of Rol)

End Class
