'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_FuncionarioEstadosConsolidados
    Public Property Id As Nullable(Of Integer)
    Public Property FuncionarioId As Integer
    Public Property TipoEstadoNombre As String
    Public Property FechaDesde As Nullable(Of Date)
    Public Property FechaHasta As Nullable(Of Date)
    Public Property Observaciones As String
    Public Property Origen As String
    Public Property TipoEstadoTransitorioId As Integer

End Class
