'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_LicenciasCompletas
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property TipoLicenciaId As Integer
    Public Property CI As String
    Public Property NombreFuncionario As String
    Public Property TipoLicencia As String
    Public Property FechaInicio As Date
    Public Property FechaFin As Date
    Public Property Estado As String
    Public Property Comentario As String

End Class
