'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_NovedadesAgrupadas
    Public Property Id As Integer
    Public Property Fecha As Date
    Public Property Resumen As String
    Public Property Funcionarios As String
    Public Property Estado As String

End Class
