'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuditoriaCambios
    Public Property Id As Integer
    Public Property FechaHora As Date
    Public Property TipoOperacion As String
    Public Property UsuarioAccion As String
    Public Property TablaNombre As String
    Public Property RegistroId As String
    Public Property CampoNombre As String
    Public Property ValorAnterior As String
    Public Property ValorNuevo As String

End Class
