'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PuestoTrabajo
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Activo As Boolean
    Public Property CreatedAt As Date
    Public Property TipoViaticoId As Nullable(Of Integer)
    Public Property AreaTrabajoId As Nullable(Of Integer)

    Public Overridable Property AreaTrabajo As AreaTrabajo
    Public Overridable Property Funcionario As ICollection(Of Funcionario) = New HashSet(Of Funcionario)
    Public Overridable Property TipoViatico As TipoViatico

End Class
