'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property Id As Integer
    Public Property FuncionarioId As Nullable(Of Integer)
    Public Property UserName As String
    Public Property PasswordHash As Byte()
    Public Property PasswordSalt As Byte()
    Public Property Email As String
    Public Property RolId As Byte
    Public Property IsActive As Boolean
    Public Property LastLoginAt As Nullable(Of Date)
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property RolUsuario As RolUsuario

End Class
