'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_LicenciasConFuncionario
    Public Property Id As Integer
    Public Property CI As String
    Public Property NombreFuncionario As String
    Public Property TipoLicencia As String
    Public Property inicio As Date
    Public Property finaliza As Date
    Public Property estado As String

End Class
