'------------------------------------------------------------------------------
' <auto-generated>
'     Modernized designer code for frmFuncionarioCrear.
'     NOTE:  The Windows Forms designer can still regenerate this file. You should
'     place custom logic in frmFuncionarioCrear.vb (code‑behind).
' </auto-generated>
'------------------------------------------------------------------------------

<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class frmFuncionarioCrear
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso (components IsNot Nothing) Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.TableLayoutPanel1 = New System.Windows.Forms.TableLayoutPanel()
        Me.lblCI = New System.Windows.Forms.Label()
        Me.txtCI = New System.Windows.Forms.TextBox()
        Me.lblNombre = New System.Windows.Forms.Label()
        Me.txtNombre = New System.Windows.Forms.TextBox()
        Me.lblFechaIngreso = New System.Windows.Forms.Label()
        Me.dtpFechaIngreso = New System.Windows.Forms.DateTimePicker()
        Me.lblTipoFuncionario = New System.Windows.Forms.Label()
        Me.lblCargo = New System.Windows.Forms.Label()
        Me.lblRutaFoto = New System.Windows.Forms.Label()
        Me.pnlFoto = New System.Windows.Forms.Panel()
        Me.txtRutaFoto = New System.Windows.Forms.TextBox()
        Me.btnSeleccionarFoto = New System.Windows.Forms.Button()
        Me.cboCargo = New System.Windows.Forms.ComboBox()
        Me.cboTipoFuncionario = New System.Windows.Forms.ComboBox()
        Me.pbFoto = New System.Windows.Forms.PictureBox()
        Me.FlowLayoutPanel1 = New System.Windows.Forms.FlowLayoutPanel()
        Me.btnGuardar = New System.Windows.Forms.Button()
        Me.btnCancelar = New System.Windows.Forms.Button()
        Me.chkActivo = New System.Windows.Forms.CheckBox()
        Me.TableLayoutPanel1.SuspendLayout()
        Me.pnlFoto.SuspendLayout()
        CType(Me.pbFoto, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.FlowLayoutPanel1.SuspendLayout()
        Me.SuspendLayout()
        '
        'TableLayoutPanel1
        '
        Me.TableLayoutPanel1.ColumnCount = 2
        Me.TableLayoutPanel1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle())
        Me.TableLayoutPanel1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.TableLayoutPanel1.Controls.Add(Me.lblCI, 0, 1)
        Me.TableLayoutPanel1.Controls.Add(Me.txtCI, 1, 1)
        Me.TableLayoutPanel1.Controls.Add(Me.lblNombre, 0, 2)
        Me.TableLayoutPanel1.Controls.Add(Me.txtNombre, 1, 2)
        Me.TableLayoutPanel1.Controls.Add(Me.lblFechaIngreso, 0, 4)
        Me.TableLayoutPanel1.Controls.Add(Me.dtpFechaIngreso, 1, 4)
        Me.TableLayoutPanel1.Controls.Add(Me.lblTipoFuncionario, 0, 5)
        Me.TableLayoutPanel1.Controls.Add(Me.lblCargo, 0, 6)
        Me.TableLayoutPanel1.Controls.Add(Me.lblRutaFoto, 0, 7)
        Me.TableLayoutPanel1.Controls.Add(Me.pnlFoto, 1, 7)
        Me.TableLayoutPanel1.Controls.Add(Me.cboCargo, 1, 6)
        Me.TableLayoutPanel1.Controls.Add(Me.cboTipoFuncionario, 1, 5)
        Me.TableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Top
        Me.TableLayoutPanel1.Location = New System.Drawing.Point(13, 13)
        Me.TableLayoutPanel1.Margin = New System.Windows.Forms.Padding(2)
        Me.TableLayoutPanel1.Name = "TableLayoutPanel1"
        Me.TableLayoutPanel1.RowCount = 8
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanel1.Size = New System.Drawing.Size(476, 243)
        Me.TableLayoutPanel1.TabIndex = 0
        '
        'lblCI
        '
        Me.lblCI.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblCI.AutoSize = True
        Me.lblCI.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblCI.Location = New System.Drawing.Point(118, 2)
        Me.lblCI.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblCI.Name = "lblCI"
        Me.lblCI.Size = New System.Drawing.Size(31, 19)
        Me.lblCI.TabIndex = 1
        Me.lblCI.Text = "C.I.:"
        '
        'txtCI
        '
        Me.txtCI.Anchor = System.Windows.Forms.AnchorStyles.Left
        Me.txtCI.Location = New System.Drawing.Point(153, 2)
        Me.txtCI.Margin = New System.Windows.Forms.Padding(2)
        Me.txtCI.Name = "txtCI"
        Me.txtCI.Size = New System.Drawing.Size(172, 20)
        Me.txtCI.TabIndex = 2
        '
        'lblNombre
        '
        Me.lblNombre.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblNombre.AutoSize = True
        Me.lblNombre.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblNombre.Location = New System.Drawing.Point(87, 26)
        Me.lblNombre.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblNombre.Name = "lblNombre"
        Me.lblNombre.Size = New System.Drawing.Size(62, 19)
        Me.lblNombre.TabIndex = 2
        Me.lblNombre.Text = "Nombre:"
        '
        'txtNombre
        '
        Me.txtNombre.Anchor = System.Windows.Forms.AnchorStyles.Left
        Me.txtNombre.Location = New System.Drawing.Point(153, 26)
        Me.txtNombre.Margin = New System.Windows.Forms.Padding(2)
        Me.txtNombre.Name = "txtNombre"
        Me.txtNombre.Size = New System.Drawing.Size(229, 20)
        Me.txtNombre.TabIndex = 3
        '
        'lblFechaIngreso
        '
        Me.lblFechaIngreso.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblFechaIngreso.AutoSize = True
        Me.lblFechaIngreso.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblFechaIngreso.Location = New System.Drawing.Point(34, 50)
        Me.lblFechaIngreso.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblFechaIngreso.Name = "lblFechaIngreso"
        Me.lblFechaIngreso.Size = New System.Drawing.Size(115, 19)
        Me.lblFechaIngreso.TabIndex = 4
        Me.lblFechaIngreso.Text = "Fecha de ingreso:"
        '
        'dtpFechaIngreso
        '
        Me.dtpFechaIngreso.Anchor = System.Windows.Forms.AnchorStyles.Left
        Me.dtpFechaIngreso.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.dtpFechaIngreso.Location = New System.Drawing.Point(153, 50)
        Me.dtpFechaIngreso.Margin = New System.Windows.Forms.Padding(2)
        Me.dtpFechaIngreso.Name = "dtpFechaIngreso"
        Me.dtpFechaIngreso.Size = New System.Drawing.Size(104, 20)
        Me.dtpFechaIngreso.TabIndex = 5
        '
        'lblTipoFuncionario
        '
        Me.lblTipoFuncionario.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblTipoFuncionario.AutoSize = True
        Me.lblTipoFuncionario.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblTipoFuncionario.Location = New System.Drawing.Point(2, 75)
        Me.lblTipoFuncionario.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblTipoFuncionario.Name = "lblTipoFuncionario"
        Me.lblTipoFuncionario.Size = New System.Drawing.Size(147, 19)
        Me.lblTipoFuncionario.TabIndex = 5
        Me.lblTipoFuncionario.Text = "ID Tipo de funcionario:"
        '
        'lblCargo
        '
        Me.lblCargo.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblCargo.AutoSize = True
        Me.lblCargo.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblCargo.Location = New System.Drawing.Point(100, 100)
        Me.lblCargo.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblCargo.Name = "lblCargo"
        Me.lblCargo.Size = New System.Drawing.Size(49, 19)
        Me.lblCargo.TabIndex = 6
        Me.lblCargo.Text = "Cargo:"
        '
        'lblRutaFoto
        '
        Me.lblRutaFoto.Anchor = System.Windows.Forms.AnchorStyles.Right
        Me.lblRutaFoto.AutoSize = True
        Me.lblRutaFoto.Font = New System.Drawing.Font("Segoe UI", 10.0!)
        Me.lblRutaFoto.Location = New System.Drawing.Point(78, 173)
        Me.lblRutaFoto.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.lblRutaFoto.Name = "lblRutaFoto"
        Me.lblRutaFoto.Size = New System.Drawing.Size(71, 19)
        Me.lblRutaFoto.TabIndex = 7
        Me.lblRutaFoto.Text = "Foto (op.):"
        '
        'pnlFoto
        '
        Me.pnlFoto.Controls.Add(Me.txtRutaFoto)
        Me.pnlFoto.Controls.Add(Me.btnSeleccionarFoto)
        Me.pnlFoto.Location = New System.Drawing.Point(151, 122)
        Me.pnlFoto.Margin = New System.Windows.Forms.Padding(0)
        Me.pnlFoto.Name = "pnlFoto"
        Me.pnlFoto.Size = New System.Drawing.Size(325, 26)
        Me.pnlFoto.TabIndex = 8
        '
        'txtRutaFoto
        '
        Me.txtRutaFoto.Location = New System.Drawing.Point(0, 2)
        Me.txtRutaFoto.Margin = New System.Windows.Forms.Padding(2)
        Me.txtRutaFoto.Name = "txtRutaFoto"
        Me.txtRutaFoto.ReadOnly = True
        Me.txtRutaFoto.Size = New System.Drawing.Size(244, 20)
        Me.txtRutaFoto.TabIndex = 0
        '
        'btnSeleccionarFoto
        '
        Me.btnSeleccionarFoto.Location = New System.Drawing.Point(248, 0)
        Me.btnSeleccionarFoto.Margin = New System.Windows.Forms.Padding(2)
        Me.btnSeleccionarFoto.Name = "btnSeleccionarFoto"
        Me.btnSeleccionarFoto.Size = New System.Drawing.Size(68, 26)
        Me.btnSeleccionarFoto.TabIndex = 15
        Me.btnSeleccionarFoto.Text = "Buscar…"
        Me.btnSeleccionarFoto.UseVisualStyleBackColor = True
        '
        'cboCargo
        '
        Me.cboCargo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cboCargo.FormattingEnabled = True
        Me.cboCargo.Location = New System.Drawing.Point(153, 99)
        Me.cboCargo.Margin = New System.Windows.Forms.Padding(2)
        Me.cboCargo.Name = "cboCargo"
        Me.cboCargo.Size = New System.Drawing.Size(113, 21)
        Me.cboCargo.TabIndex = 9
        '
        'cboTipoFuncionario
        '
        Me.cboTipoFuncionario.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cboTipoFuncionario.FormattingEnabled = True
        Me.cboTipoFuncionario.Location = New System.Drawing.Point(153, 74)
        Me.cboTipoFuncionario.Margin = New System.Windows.Forms.Padding(2)
        Me.cboTipoFuncionario.Name = "cboTipoFuncionario"
        Me.cboTipoFuncionario.Size = New System.Drawing.Size(113, 21)
        Me.cboTipoFuncionario.TabIndex = 10
        '
        'pbFoto
        '
        Me.pbFoto.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.pbFoto.Location = New System.Drawing.Point(390, 15)
        Me.pbFoto.Margin = New System.Windows.Forms.Padding(2)
        Me.pbFoto.Name = "pbFoto"
        Me.pbFoto.Size = New System.Drawing.Size(94, 120)
        Me.pbFoto.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.pbFoto.TabIndex = 0
        Me.pbFoto.TabStop = False
        '
        'FlowLayoutPanel1
        '
        Me.FlowLayoutPanel1.AutoSize = True
        Me.FlowLayoutPanel1.Controls.Add(Me.btnGuardar)
        Me.FlowLayoutPanel1.Controls.Add(Me.btnCancelar)
        Me.FlowLayoutPanel1.Controls.Add(Me.chkActivo)
        Me.FlowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Bottom
        Me.FlowLayoutPanel1.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft
        Me.FlowLayoutPanel1.Location = New System.Drawing.Point(13, 315)
        Me.FlowLayoutPanel1.Margin = New System.Windows.Forms.Padding(2)
        Me.FlowLayoutPanel1.Name = "FlowLayoutPanel1"
        Me.FlowLayoutPanel1.Padding = New System.Windows.Forms.Padding(0, 4, 13, 0)
        Me.FlowLayoutPanel1.Size = New System.Drawing.Size(476, 38)
        Me.FlowLayoutPanel1.TabIndex = 1
        '
        'btnGuardar
        '
        Me.btnGuardar.AutoSize = True
        Me.btnGuardar.Location = New System.Drawing.Point(385, 6)
        Me.btnGuardar.Margin = New System.Windows.Forms.Padding(2)
        Me.btnGuardar.Name = "btnGuardar"
        Me.btnGuardar.Padding = New System.Windows.Forms.Padding(8, 2, 8, 2)
        Me.btnGuardar.Size = New System.Drawing.Size(76, 30)
        Me.btnGuardar.TabIndex = 16
        Me.btnGuardar.Text = "Guardar"
        Me.btnGuardar.UseVisualStyleBackColor = True
        '
        'btnCancelar
        '
        Me.btnCancelar.AutoSize = True
        Me.btnCancelar.Location = New System.Drawing.Point(303, 6)
        Me.btnCancelar.Margin = New System.Windows.Forms.Padding(2)
        Me.btnCancelar.Name = "btnCancelar"
        Me.btnCancelar.Padding = New System.Windows.Forms.Padding(8, 2, 8, 2)
        Me.btnCancelar.Size = New System.Drawing.Size(78, 30)
        Me.btnCancelar.TabIndex = 17
        Me.btnCancelar.Text = "Cancelar"
        Me.btnCancelar.UseVisualStyleBackColor = True
        '
        'chkActivo
        '
        Me.chkActivo.AutoSize = True
        Me.chkActivo.Checked = True
        Me.chkActivo.CheckState = System.Windows.Forms.CheckState.Checked
        Me.chkActivo.Location = New System.Drawing.Point(186, 6)
        Me.chkActivo.Margin = New System.Windows.Forms.Padding(2)
        Me.chkActivo.Name = "chkActivo"
        Me.chkActivo.Size = New System.Drawing.Size(113, 17)
        Me.chkActivo.TabIndex = 18
        Me.chkActivo.Text = "Funcionario activo"
        Me.chkActivo.UseVisualStyleBackColor = True
        '
        'frmFuncionarioCrear
        '
        Me.AcceptButton = Me.btnGuardar
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(502, 366)
        Me.Controls.Add(Me.pbFoto)
        Me.Controls.Add(Me.FlowLayoutPanel1)
        Me.Controls.Add(Me.TableLayoutPanel1)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog
        Me.Margin = New System.Windows.Forms.Padding(2)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "frmFuncionarioCrear"
        Me.Padding = New System.Windows.Forms.Padding(13)
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Nuevo funcionario"
        Me.TableLayoutPanel1.ResumeLayout(False)
        Me.TableLayoutPanel1.PerformLayout()
        Me.pnlFoto.ResumeLayout(False)
        Me.pnlFoto.PerformLayout()
        CType(Me.pbFoto, System.ComponentModel.ISupportInitialize).EndInit()
        Me.FlowLayoutPanel1.ResumeLayout(False)
        Me.FlowLayoutPanel1.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents TableLayoutPanel1 As System.Windows.Forms.TableLayoutPanel
    Friend WithEvents lblCI As System.Windows.Forms.Label
    Friend WithEvents txtCI As System.Windows.Forms.TextBox
    Friend WithEvents lblNombre As System.Windows.Forms.Label
    Friend WithEvents txtNombre As System.Windows.Forms.TextBox
    Friend WithEvents lblFechaIngreso As System.Windows.Forms.Label
    Friend WithEvents dtpFechaIngreso As System.Windows.Forms.DateTimePicker
    Friend WithEvents lblTipoFuncionario As System.Windows.Forms.Label
    Friend WithEvents lblCargo As System.Windows.Forms.Label
    Friend WithEvents lblRutaFoto As System.Windows.Forms.Label
    Friend WithEvents pnlFoto As System.Windows.Forms.Panel
    Friend WithEvents txtRutaFoto As System.Windows.Forms.TextBox
    Friend WithEvents btnSeleccionarFoto As System.Windows.Forms.Button
    Friend WithEvents pbFoto As System.Windows.Forms.PictureBox
    Friend WithEvents FlowLayoutPanel1 As System.Windows.Forms.FlowLayoutPanel
    Friend WithEvents btnGuardar As System.Windows.Forms.Button
    Friend WithEvents btnCancelar As System.Windows.Forms.Button
    Friend WithEvents cboCargo As ComboBox
    Friend WithEvents cboTipoFuncionario As ComboBox
    Friend WithEvents chkActivo As CheckBox
End Class
