'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por el Diseñador de formularios de Windows.
'     No lo modifique manualmente; use el Diseñador para cambiarlo.
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class frmFuncionarioBuscar
    Inherits System.Windows.Forms.Form

#Region "Dispose"
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(disposing As Boolean)
        Try
            If disposing AndAlso (components IsNot Nothing) Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub
#End Region

    Private components As System.ComponentModel.IContainer

    '======================================================================
    '                       ¡InitializeComponent!
    '======================================================================
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.mainLayout = New System.Windows.Forms.TableLayoutPanel()
        Me.grpFiltros = New System.Windows.Forms.GroupBox()
        Me.flowFiltros = New System.Windows.Forms.FlowLayoutPanel()
        Me.lblBuscar = New System.Windows.Forms.Label()
        Me.txtBusqueda = New System.Windows.Forms.TextBox()
        Me.btnBuscar = New System.Windows.Forms.Button()
        Me.dgvResultados = New System.Windows.Forms.DataGridView()
        Me.grpDetalle = New System.Windows.Forms.GroupBox()
        Me.detailLayout = New System.Windows.Forms.TableLayoutPanel()
        Me.lblPresenciaHeader = New System.Windows.Forms.Label()
        Me.lblPresencia = New System.Windows.Forms.Label()
        Me.pbFotoDetalle = New System.Windows.Forms.PictureBox()
        Me.lblCIHeader = New System.Windows.Forms.Label()
        Me.lblCI = New System.Windows.Forms.Label()
        Me.lblNombreHeader = New System.Windows.Forms.Label()
        Me.lblNombreCompleto = New System.Windows.Forms.Label()
        Me.lblCargoHeader = New System.Windows.Forms.Label()
        Me.lblCargo = New System.Windows.Forms.Label()
        Me.lblTipoHeader = New System.Windows.Forms.Label()
        Me.lblTipo = New System.Windows.Forms.Label()
        Me.lblFechaIngresoHeader = New System.Windows.Forms.Label()
        Me.lblFechaIngreso = New System.Windows.Forms.Label()
        Me.chkActivoDetalle = New System.Windows.Forms.CheckBox()
        Me.mainLayout.SuspendLayout()
        Me.grpFiltros.SuspendLayout()
        Me.flowFiltros.SuspendLayout()
        CType(Me.dgvResultados, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.grpDetalle.SuspendLayout()
        Me.detailLayout.SuspendLayout()
        CType(Me.pbFotoDetalle, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'mainLayout
        '
        Me.mainLayout.ColumnCount = 2
        Me.mainLayout.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50.29656!))
        Me.mainLayout.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49.70344!))
        Me.mainLayout.Controls.Add(Me.grpFiltros, 0, 0)
        Me.mainLayout.Controls.Add(Me.dgvResultados, 0, 1)
        Me.mainLayout.Controls.Add(Me.grpDetalle, 1, 1)
        Me.mainLayout.Dock = System.Windows.Forms.DockStyle.Fill
        Me.mainLayout.Location = New System.Drawing.Point(0, 0)
        Me.mainLayout.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.mainLayout.Name = "mainLayout"
        Me.mainLayout.RowCount = 2
        Me.mainLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.mainLayout.RowStyles.Add(New System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.mainLayout.Size = New System.Drawing.Size(1124, 715)
        Me.mainLayout.TabIndex = 0
        '
        'grpFiltros
        '
        Me.grpFiltros.AutoSize = True
        Me.grpFiltros.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink
        Me.mainLayout.SetColumnSpan(Me.grpFiltros, 2)
        Me.grpFiltros.Controls.Add(Me.flowFiltros)
        Me.grpFiltros.Dock = System.Windows.Forms.DockStyle.Top
        Me.grpFiltros.Location = New System.Drawing.Point(4, 4)
        Me.grpFiltros.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.grpFiltros.Name = "grpFiltros"
        Me.grpFiltros.Padding = New System.Windows.Forms.Padding(12, 11, 12, 11)
        Me.grpFiltros.Size = New System.Drawing.Size(1116, 69)
        Me.grpFiltros.TabIndex = 0
        Me.grpFiltros.TabStop = False
        Me.grpFiltros.Text = "Filtros de búsqueda"
        '
        'flowFiltros
        '
        Me.flowFiltros.AutoSize = True
        Me.flowFiltros.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink
        Me.flowFiltros.Controls.Add(Me.lblBuscar)
        Me.flowFiltros.Controls.Add(Me.txtBusqueda)
        Me.flowFiltros.Controls.Add(Me.btnBuscar)
        Me.flowFiltros.Dock = System.Windows.Forms.DockStyle.Fill
        Me.flowFiltros.Location = New System.Drawing.Point(12, 26)
        Me.flowFiltros.Margin = New System.Windows.Forms.Padding(0)
        Me.flowFiltros.Name = "flowFiltros"
        Me.flowFiltros.Size = New System.Drawing.Size(1092, 32)
        Me.flowFiltros.TabIndex = 0
        Me.flowFiltros.WrapContents = False
        '
        'lblBuscar
        '
        Me.lblBuscar.AutoSize = True
        Me.lblBuscar.Location = New System.Drawing.Point(4, 0)
        Me.lblBuscar.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblBuscar.Name = "lblBuscar"
        Me.lblBuscar.Size = New System.Drawing.Size(49, 16)
        Me.lblBuscar.TabIndex = 4
        Me.lblBuscar.Text = "Buscar"
        '
        'txtBusqueda
        '
        Me.txtBusqueda.Location = New System.Drawing.Point(61, 4)
        Me.txtBusqueda.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.txtBusqueda.Name = "txtBusqueda"
        Me.txtBusqueda.Size = New System.Drawing.Size(205, 22)
        Me.txtBusqueda.TabIndex = 5
        '
        'btnBuscar
        '
        Me.btnBuscar.AutoSize = True
        Me.btnBuscar.Location = New System.Drawing.Point(287, 0)
        Me.btnBuscar.Margin = New System.Windows.Forms.Padding(17, 0, 0, 0)
        Me.btnBuscar.Name = "btnBuscar"
        Me.btnBuscar.Size = New System.Drawing.Size(85, 32)
        Me.btnBuscar.TabIndex = 6
        Me.btnBuscar.Text = "Buscar"
        '
        'dgvResultados
        '
        Me.dgvResultados.AllowUserToDeleteRows = False
        Me.dgvResultados.AllowUserToResizeColumns = False
        Me.dgvResultados.AllowUserToResizeRows = False
        Me.dgvResultados.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells
        Me.dgvResultados.ColumnHeadersHeight = 29
        Me.dgvResultados.Dock = System.Windows.Forms.DockStyle.Fill
        Me.dgvResultados.Location = New System.Drawing.Point(4, 81)
        Me.dgvResultados.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.dgvResultados.MultiSelect = False
        Me.dgvResultados.Name = "dgvResultados"
        Me.dgvResultados.ReadOnly = True
        Me.dgvResultados.RowHeadersWidth = 51
        Me.dgvResultados.RowTemplate.Height = 70
        Me.dgvResultados.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.dgvResultados.Size = New System.Drawing.Size(557, 630)
        Me.dgvResultados.TabIndex = 1
        '
        'grpDetalle
        '
        Me.grpDetalle.Controls.Add(Me.detailLayout)
        Me.grpDetalle.Dock = System.Windows.Forms.DockStyle.Fill
        Me.grpDetalle.Location = New System.Drawing.Point(569, 81)
        Me.grpDetalle.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.grpDetalle.Name = "grpDetalle"
        Me.grpDetalle.Padding = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.grpDetalle.Size = New System.Drawing.Size(551, 630)
        Me.grpDetalle.TabIndex = 2
        Me.grpDetalle.TabStop = False
        Me.grpDetalle.Text = "Detalle del funcionario"
        '
        'detailLayout
        '
        Me.detailLayout.ColumnCount = 2
        Me.detailLayout.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 115.0!))
        Me.detailLayout.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.detailLayout.Controls.Add(Me.lblPresenciaHeader, 0, 7)
        Me.detailLayout.Controls.Add(Me.lblPresencia, 1, 7)
        Me.detailLayout.Controls.Add(Me.pbFotoDetalle, 0, 0)
        Me.detailLayout.Controls.Add(Me.lblCIHeader, 0, 2)
        Me.detailLayout.Controls.Add(Me.lblCI, 1, 2)
        Me.detailLayout.Controls.Add(Me.lblNombreHeader, 0, 3)
        Me.detailLayout.Controls.Add(Me.lblNombreCompleto, 1, 3)
        Me.detailLayout.Controls.Add(Me.lblCargoHeader, 0, 4)
        Me.detailLayout.Controls.Add(Me.lblCargo, 1, 4)
        Me.detailLayout.Controls.Add(Me.lblTipoHeader, 0, 5)
        Me.detailLayout.Controls.Add(Me.lblTipo, 1, 5)
        Me.detailLayout.Controls.Add(Me.lblFechaIngresoHeader, 0, 6)
        Me.detailLayout.Controls.Add(Me.lblFechaIngreso, 1, 6)
        Me.detailLayout.Controls.Add(Me.chkActivoDetalle, 0, 1)
        Me.detailLayout.Dock = System.Windows.Forms.DockStyle.Fill
        Me.detailLayout.Location = New System.Drawing.Point(4, 19)
        Me.detailLayout.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.detailLayout.Name = "detailLayout"
        Me.detailLayout.RowCount = 9
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.detailLayout.RowStyles.Add(New System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25.0!))
        Me.detailLayout.Size = New System.Drawing.Size(543, 607)
        Me.detailLayout.TabIndex = 0
        '
        'lblPresenciaHeader
        '
        Me.lblPresenciaHeader.AutoSize = True
        Me.lblPresenciaHeader.Location = New System.Drawing.Point(4, 475)
        Me.lblPresenciaHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblPresenciaHeader.Name = "lblPresenciaHeader"
        Me.lblPresenciaHeader.Size = New System.Drawing.Size(68, 16)
        Me.lblPresenciaHeader.TabIndex = 14
        Me.lblPresenciaHeader.Text = "Presencia"
        '
        'lblPresencia
        '
        Me.lblPresencia.AutoSize = True
        Me.lblPresencia.Location = New System.Drawing.Point(119, 475)
        Me.lblPresencia.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblPresencia.Name = "lblPresencia"
        Me.lblPresencia.Size = New System.Drawing.Size(0, 16)
        Me.lblPresencia.TabIndex = 15
        '
        'pbFotoDetalle
        '
        Me.pbFotoDetalle.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.detailLayout.SetColumnSpan(Me.pbFotoDetalle, 2)
        Me.pbFotoDetalle.Location = New System.Drawing.Point(4, 4)
        Me.pbFotoDetalle.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.pbFotoDetalle.Name = "pbFotoDetalle"
        Me.pbFotoDetalle.Size = New System.Drawing.Size(535, 359)
        Me.pbFotoDetalle.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom
        Me.pbFotoDetalle.TabIndex = 0
        Me.pbFotoDetalle.TabStop = False
        '
        'lblCIHeader
        '
        Me.lblCIHeader.AutoSize = True
        Me.lblCIHeader.Location = New System.Drawing.Point(4, 395)
        Me.lblCIHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblCIHeader.Name = "lblCIHeader"
        Me.lblCIHeader.Size = New System.Drawing.Size(22, 16)
        Me.lblCIHeader.TabIndex = 3
        Me.lblCIHeader.Text = "CI:"
        '
        'lblCI
        '
        Me.lblCI.AutoSize = True
        Me.lblCI.Location = New System.Drawing.Point(119, 395)
        Me.lblCI.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblCI.Name = "lblCI"
        Me.lblCI.Size = New System.Drawing.Size(0, 16)
        Me.lblCI.TabIndex = 4
        '
        'lblNombreHeader
        '
        Me.lblNombreHeader.AutoSize = True
        Me.lblNombreHeader.Location = New System.Drawing.Point(4, 411)
        Me.lblNombreHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblNombreHeader.Name = "lblNombreHeader"
        Me.lblNombreHeader.Size = New System.Drawing.Size(59, 16)
        Me.lblNombreHeader.TabIndex = 5
        Me.lblNombreHeader.Text = "Nombre:"
        '
        'lblNombreCompleto
        '
        Me.lblNombreCompleto.AutoSize = True
        Me.lblNombreCompleto.Location = New System.Drawing.Point(119, 411)
        Me.lblNombreCompleto.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblNombreCompleto.Name = "lblNombreCompleto"
        Me.lblNombreCompleto.Size = New System.Drawing.Size(0, 16)
        Me.lblNombreCompleto.TabIndex = 6
        '
        'lblCargoHeader
        '
        Me.lblCargoHeader.AutoSize = True
        Me.lblCargoHeader.Location = New System.Drawing.Point(4, 427)
        Me.lblCargoHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblCargoHeader.Name = "lblCargoHeader"
        Me.lblCargoHeader.Size = New System.Drawing.Size(47, 16)
        Me.lblCargoHeader.TabIndex = 7
        Me.lblCargoHeader.Text = "Cargo:"
        '
        'lblCargo
        '
        Me.lblCargo.AutoSize = True
        Me.lblCargo.Location = New System.Drawing.Point(119, 427)
        Me.lblCargo.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblCargo.Name = "lblCargo"
        Me.lblCargo.Size = New System.Drawing.Size(0, 16)
        Me.lblCargo.TabIndex = 8
        '
        'lblTipoHeader
        '
        Me.lblTipoHeader.AutoSize = True
        Me.lblTipoHeader.Location = New System.Drawing.Point(4, 443)
        Me.lblTipoHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblTipoHeader.Name = "lblTipoHeader"
        Me.lblTipoHeader.Size = New System.Drawing.Size(38, 16)
        Me.lblTipoHeader.TabIndex = 9
        Me.lblTipoHeader.Text = "Tipo:"
        '
        'lblTipo
        '
        Me.lblTipo.AutoSize = True
        Me.lblTipo.Location = New System.Drawing.Point(119, 443)
        Me.lblTipo.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblTipo.Name = "lblTipo"
        Me.lblTipo.Size = New System.Drawing.Size(0, 16)
        Me.lblTipo.TabIndex = 10
        '
        'lblFechaIngresoHeader
        '
        Me.lblFechaIngresoHeader.AutoSize = True
        Me.lblFechaIngresoHeader.Location = New System.Drawing.Point(4, 459)
        Me.lblFechaIngresoHeader.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblFechaIngresoHeader.Name = "lblFechaIngresoHeader"
        Me.lblFechaIngresoHeader.Size = New System.Drawing.Size(96, 16)
        Me.lblFechaIngresoHeader.TabIndex = 11
        Me.lblFechaIngresoHeader.Text = "Fecha ingreso:"
        '
        'lblFechaIngreso
        '
        Me.lblFechaIngreso.AutoSize = True
        Me.lblFechaIngreso.Location = New System.Drawing.Point(119, 459)
        Me.lblFechaIngreso.Margin = New System.Windows.Forms.Padding(4, 0, 4, 0)
        Me.lblFechaIngreso.Name = "lblFechaIngreso"
        Me.lblFechaIngreso.Size = New System.Drawing.Size(0, 16)
        Me.lblFechaIngreso.TabIndex = 12
        '
        'chkActivoDetalle
        '
        Me.chkActivoDetalle.AutoSize = True
        Me.detailLayout.SetColumnSpan(Me.chkActivoDetalle, 2)
        Me.chkActivoDetalle.Enabled = False
        Me.chkActivoDetalle.Location = New System.Drawing.Point(4, 371)
        Me.chkActivoDetalle.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.chkActivoDetalle.Name = "chkActivoDetalle"
        Me.chkActivoDetalle.Size = New System.Drawing.Size(66, 20)
        Me.chkActivoDetalle.TabIndex = 13
        Me.chkActivoDetalle.Text = "Activo"
        '
        'frmFuncionarioBuscar
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 16.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1124, 715)
        Me.Controls.Add(Me.mainLayout)
        Me.Margin = New System.Windows.Forms.Padding(4, 4, 4, 4)
        Me.Name = "frmFuncionarioBuscar"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Buscar funcionario"
        Me.mainLayout.ResumeLayout(False)
        Me.mainLayout.PerformLayout()
        Me.grpFiltros.ResumeLayout(False)
        Me.grpFiltros.PerformLayout()
        Me.flowFiltros.ResumeLayout(False)
        Me.flowFiltros.PerformLayout()
        CType(Me.dgvResultados, System.ComponentModel.ISupportInitialize).EndInit()
        Me.grpDetalle.ResumeLayout(False)
        Me.detailLayout.ResumeLayout(False)
        Me.detailLayout.PerformLayout()
        CType(Me.pbFotoDetalle, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub

    '==================== Declaraciones Friend WithEvents ====================
    Friend WithEvents mainLayout As TableLayoutPanel
    Friend WithEvents grpFiltros As GroupBox
    Friend WithEvents flowFiltros As FlowLayoutPanel
    Friend WithEvents lblBuscar As Label
    Friend WithEvents txtBusqueda As TextBox
    Friend WithEvents btnBuscar As Button
    Friend WithEvents dgvResultados As DataGridView
    Friend WithEvents grpDetalle As GroupBox
    Friend WithEvents detailLayout As TableLayoutPanel
    Friend WithEvents pbFotoDetalle As PictureBox
    Friend WithEvents lblCIHeader As Label
    Friend WithEvents lblCI As Label
    Friend WithEvents lblNombreHeader As Label
    Friend WithEvents lblNombreCompleto As Label
    Friend WithEvents lblCargoHeader As Label
    Friend WithEvents lblCargo As Label
    Friend WithEvents lblTipoHeader As Label
    Friend WithEvents lblTipo As Label
    Friend WithEvents lblFechaIngresoHeader As Label
    Friend WithEvents lblFechaIngreso As Label
    Friend WithEvents chkActivoDetalle As CheckBox
    Friend WithEvents lblPresenciaHeader As Label
    Friend WithEvents lblPresencia As Label
End Class

