'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class ApexEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ApexEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AreaTrabajo() As DbSet(Of AreaTrabajo)
    Public Overridable Property Arma() As DbSet(Of Arma)
    Public Overridable Property Cargo() As DbSet(Of Cargo)
    Public Overridable Property CategoriaAusencia() As DbSet(Of CategoriaAusencia)
    Public Overridable Property Escalafon() As DbSet(Of Escalafon)
    Public Overridable Property Estado() As DbSet(Of Estado)
    Public Overridable Property EstadoCivil() As DbSet(Of EstadoCivil)
    Public Overridable Property EstadoTransitorio() As DbSet(Of EstadoTransitorio)
    Public Overridable Property Funcion() As DbSet(Of Funcion)
    Public Overridable Property Funcionario() As DbSet(Of Funcionario)
    Public Overridable Property FuncionarioArma() As DbSet(Of FuncionarioArma)
    Public Overridable Property FuncionarioChaleco() As DbSet(Of FuncionarioChaleco)
    Public Overridable Property FuncionarioDispositivo() As DbSet(Of FuncionarioDispositivo)
    Public Overridable Property FuncionarioDotacion() As DbSet(Of FuncionarioDotacion)
    Public Overridable Property FuncionarioEstadoLegal() As DbSet(Of FuncionarioEstadoLegal)
    Public Overridable Property FuncionarioFotoHistorico() As DbSet(Of FuncionarioFotoHistorico)
    Public Overridable Property FuncionarioObservacion() As DbSet(Of FuncionarioObservacion)
    Public Overridable Property FuncionarioSalud() As DbSet(Of FuncionarioSalud)
    Public Overridable Property Genero() As DbSet(Of Genero)
    Public Overridable Property HistoricoCustodia() As DbSet(Of HistoricoCustodia)
    Public Overridable Property HistoricoLicencia() As DbSet(Of HistoricoLicencia)
    Public Overridable Property HistoricoNocturnidad() As DbSet(Of HistoricoNocturnidad)
    Public Overridable Property HistoricoPresentismo() As DbSet(Of HistoricoPresentismo)
    Public Overridable Property HistoricoViatico() As DbSet(Of HistoricoViatico)
    Public Overridable Property Horario() As DbSet(Of Horario)
    Public Overridable Property MapPoliciaFunc() As DbSet(Of MapPoliciaFunc)
    Public Overridable Property Movimiento() As DbSet(Of Movimiento)
    Public Overridable Property NivelEstudio() As DbSet(Of NivelEstudio)
    Public Overridable Property NotificacionEstado() As DbSet(Of NotificacionEstado)
    Public Overridable Property NotificacionPersonal() As DbSet(Of NotificacionPersonal)
    Public Overridable Property Novedad() As DbSet(Of Novedad)
    Public Overridable Property NovedadFoto() As DbSet(Of NovedadFoto)
    Public Overridable Property NovedadFuncionario() As DbSet(Of NovedadFuncionario)
    Public Overridable Property NovedadGenerada() As DbSet(Of NovedadGenerada)
    Public Overridable Property PuestoTrabajo() As DbSet(Of PuestoTrabajo)
    Public Overridable Property RegimenAlternancia() As DbSet(Of RegimenAlternancia)
    Public Overridable Property RegimenDetalle() As DbSet(Of RegimenDetalle)
    Public Overridable Property RegimenTrabajo() As DbSet(Of RegimenTrabajo)
    Public Overridable Property RolUsuario() As DbSet(Of RolUsuario)
    Public Overridable Property Seccion() As DbSet(Of Seccion)
    Public Overridable Property Semana() As DbSet(Of Semana)
    Public Overridable Property TipoEstadoTransitorio() As DbSet(Of TipoEstadoTransitorio)
    Public Overridable Property TipoFuncionario() As DbSet(Of TipoFuncionario)
    Public Overridable Property TipoLicencia() As DbSet(Of TipoLicencia)
    Public Overridable Property TipoNotificacion() As DbSet(Of TipoNotificacion)
    Public Overridable Property TipoViatico() As DbSet(Of TipoViatico)
    Public Overridable Property Turno() As DbSet(Of Turno)
    Public Overridable Property Usuario() As DbSet(Of Usuario)

    Public Overridable Function usp_CargarHistoricosPolicia() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_CargarHistoricosPolicia")
    End Function

    Public Overridable Function usp_DeleteFuncionario(funcionarioId As Nullable(Of Integer)) As Integer
        Dim funcionarioIdParameter As ObjectParameter = If(funcionarioId.HasValue, New ObjectParameter("FuncionarioId", funcionarioId), New ObjectParameter("FuncionarioId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_DeleteFuncionario", funcionarioIdParameter)
    End Function

    Public Overridable Function usp_MigrarArmas() As ObjectResult(Of usp_MigrarArmas_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_MigrarArmas_Result)("usp_MigrarArmas")
    End Function

    Public Overridable Function usp_MigrarArmasYAsignaciones() As ObjectResult(Of usp_MigrarArmasYAsignaciones_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_MigrarArmasYAsignaciones_Result)("usp_MigrarArmasYAsignaciones")
    End Function

    Public Overridable Function usp_MigrarEstadosUnificados() As ObjectResult(Of Nullable(Of Integer))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("usp_MigrarEstadosUnificados")
    End Function

    Public Overridable Function usp_MigrarFuncionariosDesdePersonal(refrescarCatalogos As Nullable(Of Boolean)) As Integer
        Dim refrescarCatalogosParameter As ObjectParameter = If(refrescarCatalogos.HasValue, New ObjectParameter("RefrescarCatalogos", refrescarCatalogos), New ObjectParameter("RefrescarCatalogos", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarFuncionariosDesdePersonal", refrescarCatalogosParameter)
    End Function

    Public Overridable Function usp_MigrarNotificaciones() As ObjectResult(Of Nullable(Of Integer))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("usp_MigrarNotificaciones")
    End Function

    Public Overridable Function usp_MigrarNovedadesDesdePersonal() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarNovedadesDesdePersonal")
    End Function

    Public Overridable Function usp_MigrarUsuarios() As ObjectResult(Of Nullable(Of Integer))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("usp_MigrarUsuarios")
    End Function

    Public Overridable Function usp_PresenciaFecha_Apex(fecha As Nullable(Of Date)) As ObjectResult(Of usp_PresenciaFecha_Apex_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_PresenciaFecha_Apex_Result)("usp_PresenciaFecha_Apex", fechaParameter)
    End Function

    Public Overridable Function usp_ProcesarEstadoNotificaciones() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_ProcesarEstadoNotificaciones")
    End Function

End Class
