'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cargo
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property Grado As Nullable(Of Integer)

    Public Overridable Property CambioDeCargoDetalle As ICollection(Of CambioDeCargoDetalle) = New HashSet(Of CambioDeCargoDetalle)
    Public Overridable Property CambioDeCargoDetalle1 As ICollection(Of CambioDeCargoDetalle) = New HashSet(Of CambioDeCargoDetalle)
    Public Overridable Property Funcionario As ICollection(Of Funcionario) = New HashSet(Of Funcionario)

End Class
