'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DotacionItem
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Activo As Boolean
    Public Property CreatedAt As Date

    Public Overridable Property FuncionarioDotacion As ICollection(Of FuncionarioDotacion) = New HashSet(Of FuncionarioDotacion)

End Class
