'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstadoTransitorioAdjunto
    Public Property Id As Integer
    Public Property EstadoTransitorioId As Integer
    Public Property NombreArchivo As String
    Public Property TipoMIME As String
    Public Property Contenido As Byte()
    Public Property FechaCreacion As Date
    Public Property Descripcion As String

    Public Overridable Property EstadoTransitorio As EstadoTransitorio

End Class
