'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstadoTransitorioAdjunto
    Public Property Id As Integer
    Public Property EstadoTransitorioId As Integer
    Public Property NombreArchivo As String
    Public Property TipoMIME As String
    Public Property Contenido As Byte()
    Public Property FechaCreacion As Date
    Public Property Descripcion As String

    Public Overridable Property EstadoTransitorio As EstadoTransitorio

End Class