'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstadoTransitorio
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property TipoEstadoTransitorioId As Integer
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property BajaDeFuncionarioDetalle As BajaDeFuncionarioDetalle
    Public Overridable Property CambioDeCargoDetalle As CambioDeCargoDetalle
    Public Overridable Property DesignacionDetalle As DesignacionDetalle
    Public Overridable Property EnfermedadDetalle As EnfermedadDetalle
    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property TipoEstadoTransitorio As TipoEstadoTransitorio
    Public Overridable Property EstadoTransitorioAdjunto As ICollection(Of EstadoTransitorioAdjunto) = New HashSet(Of EstadoTransitorioAdjunto)
    Public Overridable Property InicioDeProcesamientoDetalle As InicioDeProcesamientoDetalle
    Public Overridable Property OrdenCincoDetalle As OrdenCincoDetalle
    Public Overridable Property ReactivacionDeFuncionarioDetalle As ReactivacionDeFuncionarioDetalle
    Public Overridable Property RetenDetalle As RetenDetalle
    Public Overridable Property SancionDetalle As SancionDetalle
    Public Overridable Property SeparacionDelCargoDetalle As SeparacionDelCargoDetalle
    Public Overridable Property SumarioDetalle As SumarioDetalle
    Public Overridable Property TrasladoDetalle As TrasladoDetalle

End Class
