'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FuncionarioArma
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property Cargadores As Nullable(Of Integer)
    Public Property Municiones As Nullable(Of Integer)
    Public Property Observaciones As String
    Public Property FechaAsign As Date
    Public Property ArmaId As Integer
    Public Property Serie As String

    Public Overridable Property Arma As Arma
    Public Overridable Property Funcionario As Funcionario

End Class
