'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FuncionarioObservacion
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property Categoria As String
    Public Property Texto As String
    Public Property FechaRegistro As Date

    Public Overridable Property Funcionario As Funcionario

End Class
