'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HistoricoLicencia
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property TipoLicenciaId As Integer
    Public Property inicio As Date
    Public Property finaliza As Date
    Public Property fecha_registro As Date
    Public Property fecha_actualizado As Date
    Public Property usuario As String
    Public Property datos As String
    Public Property estado As String
    Public Property Unidad_Ejecutora As String
    Public Property Unidad_Organizativa As String
    Public Property Cantidad As Nullable(Of Integer)
    Public Property Cantidad_dentro_del_período As Nullable(Of Integer)
    Public Property Unidad As String
    Public Property Afecta_a_días As String
    Public Property C_Presentó_certificado_ As String
    Public Property Usuario_aprobó_anuló_rechazó As String
    Public Property Fecha_aprobación_anulación_rechazo As String
    Public Property Comentario As String

    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property TipoLicencia As TipoLicencia

End Class
