'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HistoricoViatico
    Public Property FuncionarioId As Integer
    Public Property Anio As Short
    Public Property Mes As Byte
    Public Property Incidencia As String
    Public Property Motivo As String

    Public Overridable Property Funcionario As Funcionario

End Class
