'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class ApexEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ApexEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AreaTrabajo() As DbSet(Of AreaTrabajo)
    Public Overridable Property Arma() As DbSet(Of Arma)
    Public Overridable Property Cargo() As DbSet(Of Cargo)
    Public Overridable Property CategoriaAusencia() As DbSet(Of CategoriaAusencia)
    Public Overridable Property DesignacionDetalle() As DbSet(Of DesignacionDetalle)
    Public Overridable Property DotacionItem() As DbSet(Of DotacionItem)
    Public Overridable Property EnfermedadDetalle() As DbSet(Of EnfermedadDetalle)
    Public Overridable Property Escalafon() As DbSet(Of Escalafon)
    Public Overridable Property Estado() As DbSet(Of Estado)
    Public Overridable Property EstadoCivil() As DbSet(Of EstadoCivil)
    Public Overridable Property EstadoTransitorio() As DbSet(Of EstadoTransitorio)
    Public Overridable Property EstadoTransitorioAdjuntos() As DbSet(Of EstadoTransitorioAdjuntos)
    Public Overridable Property Funcion() As DbSet(Of Funcion)
    Public Overridable Property Funcionario() As DbSet(Of Funcionario)
    Public Overridable Property FuncionarioArma() As DbSet(Of FuncionarioArma)
    Public Overridable Property FuncionarioChaleco() As DbSet(Of FuncionarioChaleco)
    Public Overridable Property FuncionarioDispositivo() As DbSet(Of FuncionarioDispositivo)
    Public Overridable Property FuncionarioDotacion() As DbSet(Of FuncionarioDotacion)
    Public Overridable Property FuncionarioEstadoLegal() As DbSet(Of FuncionarioEstadoLegal)
    Public Overridable Property FuncionarioFotoHistorico() As DbSet(Of FuncionarioFotoHistorico)
    Public Overridable Property FuncionarioSalud() As DbSet(Of FuncionarioSalud)
    Public Overridable Property Genero() As DbSet(Of Genero)
    Public Overridable Property HistoricoCustodia() As DbSet(Of HistoricoCustodia)
    Public Overridable Property HistoricoLicencia() As DbSet(Of HistoricoLicencia)
    Public Overridable Property HistoricoNocturnidad() As DbSet(Of HistoricoNocturnidad)
    Public Overridable Property HistoricoPresentismo() As DbSet(Of HistoricoPresentismo)
    Public Overridable Property HistoricoViatico() As DbSet(Of HistoricoViatico)
    Public Overridable Property Horario() As DbSet(Of Horario)
    Public Overridable Property MapPoliciaFunc() As DbSet(Of MapPoliciaFunc)
    Public Overridable Property Movimiento() As DbSet(Of Movimiento)
    Public Overridable Property NivelEstudio() As DbSet(Of NivelEstudio)
    Public Overridable Property Nomenclatura() As DbSet(Of Nomenclatura)
    Public Overridable Property NotificacionEstado() As DbSet(Of NotificacionEstado)
    Public Overridable Property NotificacionPersonal() As DbSet(Of NotificacionPersonal)
    Public Overridable Property Novedad() As DbSet(Of Novedad)
    Public Overridable Property NovedadFoto() As DbSet(Of NovedadFoto)
    Public Overridable Property NovedadFuncionario() As DbSet(Of NovedadFuncionario)
    Public Overridable Property NovedadGenerada() As DbSet(Of NovedadGenerada)
    Public Overridable Property OrdenCincoDetalle() As DbSet(Of OrdenCincoDetalle)
    Public Overridable Property PuestoTrabajo() As DbSet(Of PuestoTrabajo)
    Public Overridable Property RegimenAlternancia() As DbSet(Of RegimenAlternancia)
    Public Overridable Property RegimenDetalle() As DbSet(Of RegimenDetalle)
    Public Overridable Property RegimenTrabajo() As DbSet(Of RegimenTrabajo)
    Public Overridable Property RetenDetalle() As DbSet(Of RetenDetalle)
    Public Overridable Property RolUsuario() As DbSet(Of RolUsuario)
    Public Overridable Property SancionDetalle() As DbSet(Of SancionDetalle)
    Public Overridable Property Seccion() As DbSet(Of Seccion)
    Public Overridable Property Semana() As DbSet(Of Semana)
    Public Overridable Property SumarioDetalle() As DbSet(Of SumarioDetalle)
    Public Overridable Property TipoEstadoTransitorio() As DbSet(Of TipoEstadoTransitorio)
    Public Overridable Property TipoFuncionario() As DbSet(Of TipoFuncionario)
    Public Overridable Property TipoLicencia() As DbSet(Of TipoLicencia)
    Public Overridable Property TipoNotificacion() As DbSet(Of TipoNotificacion)
    Public Overridable Property TipoViatico() As DbSet(Of TipoViatico)
    Public Overridable Property Turno() As DbSet(Of Turno)
    Public Overridable Property Usuario() As DbSet(Of Usuario)
    Public Overridable Property vw_EstadosTransitoriosCompletos() As DbSet(Of vw_EstadosTransitoriosCompletos)
    Public Overridable Property vw_FuncionarioEstadosConsolidados() As DbSet(Of vw_FuncionarioEstadosConsolidados)
    Public Overridable Property vw_FuncionarioSituacionActual() As DbSet(Of vw_FuncionarioSituacionActual)
    Public Overridable Property vw_LicenciasCompletas() As DbSet(Of vw_LicenciasCompletas)
    Public Overridable Property vw_NotificacionesCompletas() As DbSet(Of vw_NotificacionesCompletas)
    Public Overridable Property vw_NovedadesAgrupadas() As DbSet(Of vw_NovedadesAgrupadas)
    Public Overridable Property vw_NovedadesCompletas() As DbSet(Of vw_NovedadesCompletas)
    Public Overridable Property vw_SancionesCompletas() As DbSet(Of vw_SancionesCompletas)

    Public Overridable Function usp_Apex_ImportarAgregadosMensuales(tipoHistorico As String, registrosAfectados As ObjectParameter) As Integer
        Dim tipoHistoricoParameter As ObjectParameter = If(tipoHistorico IsNot Nothing, New ObjectParameter("TipoHistorico", tipoHistorico), New ObjectParameter("TipoHistorico", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_Apex_ImportarAgregadosMensuales", tipoHistoricoParameter, registrosAfectados)
    End Function

    Public Overridable Function usp_Apex_ImportarDotacionFuncionario() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_Apex_ImportarDotacionFuncionario")
    End Function

    Public Overridable Function usp_Apex_ImportarLicenciasMasivas(registrosAfectados As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_Apex_ImportarLicenciasMasivas", registrosAfectados)
    End Function

    Public Overridable Function usp_CargarHistoricosPolicia() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_CargarHistoricosPolicia")
    End Function

    Public Overridable Function usp_DeleteFuncionario(funcionarioId As Nullable(Of Integer)) As Integer
        Dim funcionarioIdParameter As ObjectParameter = If(funcionarioId.HasValue, New ObjectParameter("FuncionarioId", funcionarioId), New ObjectParameter("FuncionarioId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_DeleteFuncionario", funcionarioIdParameter)
    End Function

    Public Overridable Function usp_LimpiarDatosDeApex() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_LimpiarDatosDeApex")
    End Function

    Public Overridable Function usp_MigrarArmas() As ObjectResult(Of usp_MigrarArmas_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_MigrarArmas_Result)("usp_MigrarArmas")
    End Function

    Public Overridable Function usp_MigrarArmasYAsignaciones() As ObjectResult(Of usp_MigrarArmasYAsignaciones_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_MigrarArmasYAsignaciones_Result)("usp_MigrarArmasYAsignaciones")
    End Function

    Public Overridable Function usp_MigrarDotacionesCompletas() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarDotacionesCompletas")
    End Function

    Public Overridable Function usp_MigrarEstadosTransitoriosDesdePersonal() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarEstadosTransitoriosDesdePersonal")
    End Function

    Public Overridable Function usp_MigrarEstadosUnificados() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarEstadosUnificados")
    End Function

    Public Overridable Function usp_MigrarFuncionariosDesdePersonal(refrescarCatalogos As Nullable(Of Boolean)) As Integer
        Dim refrescarCatalogosParameter As ObjectParameter = If(refrescarCatalogos.HasValue, New ObjectParameter("RefrescarCatalogos", refrescarCatalogos), New ObjectParameter("RefrescarCatalogos", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarFuncionariosDesdePersonal", refrescarCatalogosParameter)
    End Function

    Public Overridable Function usp_MigrarLicencias() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarLicencias")
    End Function

    Public Overridable Function usp_MigrarNotificaciones() As ObjectResult(Of Nullable(Of Integer))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("usp_MigrarNotificaciones")
    End Function

    Public Overridable Function usp_MigrarNovedadesDesdePersonal() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_MigrarNovedadesDesdePersonal")
    End Function

    Public Overridable Function usp_MigrarPuestosDeTrabajo() As ObjectResult(Of usp_MigrarPuestosDeTrabajo_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_MigrarPuestosDeTrabajo_Result)("usp_MigrarPuestosDeTrabajo")
    End Function

    Public Overridable Function usp_MigrarUsuarios() As ObjectResult(Of Nullable(Of Integer))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("usp_MigrarUsuarios")
    End Function

    Public Overridable Function usp_PresenciaFecha_Apex(fecha As Nullable(Of Date)) As Integer
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_PresenciaFecha_Apex", fechaParameter)
    End Function

    Public Overridable Function usp_ProcesarEstadoNotificaciones() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_ProcesarEstadoNotificaciones")
    End Function

End Class
