'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Movimiento
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property Fecha As Date
    Public Property EstadoId As Integer
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property Estado As Estado
    Public Overridable Property Funcionario As Funcionario

End Class
