'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NotificacionPersonal
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property FechaProgramada As Date
    Public Property FechaRegistro As Nullable(Of Date)
    Public Property Medio As String
    Public Property Documento As String
    Public Property ExpMinisterial As String
    Public Property ExpINR As String
    Public Property Oficina As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property TipoNotificacionId As Byte
    Public Property EstadoId As Byte

    Public Overridable Property Funcionario As Funcionario
    Public Overridable Property NotificacionEstado As NotificacionEstado
    Public Overridable Property TipoNotificacion As TipoNotificacion

End Class
