'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NovedadGenerada
    Public Property Id As Integer
    Public Property Fecha As Date
    Public Property CreatedAt As Date

    Public Overridable Property Novedad As ICollection(Of Novedad) = New HashSet(Of Novedad)
    Public Overridable Property NovedadFoto As ICollection(Of NovedadFoto) = New HashSet(Of NovedadFoto)

End Class
