'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NovedadFoto
    Public Property Id As Integer
    Public Property Foto As Byte()
    Public Property FileName As String
    Public Property CreatedAt As Date
    Public Property NovedadId As Integer

    Public Overridable Property Novedad As Novedad

End Class
