'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Novedad
    Public Property Id As Integer
    Public Property NovedadGeneradaId As Integer
    Public Property Fecha As Date
    Public Property Texto As String
    Public Property EstadoId As Nullable(Of Byte)
    Public Property CreatedAt As Date

    Public Overridable Property NotificacionEstado As NotificacionEstado
    Public Overridable Property NovedadGenerada As NovedadGenerada
    Public Overridable Property NovedadFuncionario As ICollection(Of NovedadFuncionario) = New HashSet(Of NovedadFuncionario)

End Class
