'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RegistroActividad
    Public Property Id As Integer
    Public Property FechaHora As Date
    Public Property Usuario As String
    Public Property Accion As String
    Public Property TipoEntidad As String
    Public Property EntidadId As Nullable(Of Integer)
    Public Property Descripcion As String

End Class
