'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RegimenTrabajo
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property TipoPatron As Byte
    Public Property Observaciones As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

    Public Overridable Property RegimenDetalle As ICollection(Of RegimenDetalle) = New HashSet(Of RegimenDetalle)

End Class
