'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoLicencia
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property EsAusencia As Boolean
    Public Property SuspendeViatico As Boolean
    Public Property AfectaPresentismo As Boolean
    Public Property EsHabil As Boolean
    Public Property CategoriaAusenciaId As Integer

    Public Overridable Property CategoriaAusencia As CategoriaAusencia
    Public Overridable Property HistoricoLicencia As ICollection(Of HistoricoLicencia) = New HashSet(Of HistoricoLicencia)

End Class
