'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoViatico
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property Dias As Integer
    Public Property CreatedAt As Date

    Public Overridable Property PuestoTrabajo As ICollection(Of PuestoTrabajo) = New HashSet(Of PuestoTrabajo)

End Class
