'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_EstadosTransitoriosCompletos
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property TipoEstadoTransitorioId As Integer
    Public Property CI As String
    Public Property NombreFuncionario As String
    Public Property TipoEstadoNombre As String
    Public Property FechaDesde As Date
    Public Property FechaHasta As Nullable(Of Date)
    Public Property Observaciones As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)

End Class
