'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_NotificacionesCompletas
    Public Property Id As Integer
    Public Property FuncionarioId As Integer
    Public Property TipoNotificacionId As Byte
    Public Property EstadoId As Byte
    Public Property NombreFuncionario As String
    Public Property CI As String
    Public Property TipoNotificacion As String
    Public Property Estado As String
    Public Property FechaProgramada As Date
    Public Property Texto As String
    Public Property Documento As String
    Public Property ExpMinisterial As String
    Public Property ExpINR As String
    Public Property Oficina As String

End Class
