'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_NovedadesCompletas
    Public Property Id As Integer
    Public Property NovedadGeneradaId As Integer
    Public Property Fecha As Date
    Public Property Texto As String
    Public Property EstadoId As Nullable(Of Byte)
    Public Property FuncionarioId As Nullable(Of Integer)
    Public Property NombreFuncionario As String
    Public Property CI As String
    Public Property Estado As String

End Class
